name: ManualRelease

on: workflow_dispatch

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: BuildLinux
      run: |
        go build -v ./... 
        pwd
        ls

    - name: Release
      run: gh release create ${{ env.VERSION }} -n "${{ env.MESSAGE }}" -t "${{ env.NAME }}" ${{ env.FILES }}
    
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      VERSION: "v.0.1"
      MESSAGE: "initial release of ngu optimizer"
      NAME: "initial release"
      FILES: /home/runner/work/ngu/ngu/ngu
